### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '1.840

### ISSUE THREAD

**Issue by TheCastes** [MajideND/scraping-reviews-from-googlemaps#6]
I updated the app.py after the last commit, here's the traceback:

File "/home/cristianc/Scrivania/ads-scraper/app.py", line 118, in \<module\>
    counter = counter()
              ^^^^^^^^^
  File "/home/cristianc/Scrivania/ads-scraper/app.py", line 71, in counter
    return int(int(result[0])/10)+1, dataStructreType
               ^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '1.840'

**Comment by MajideND** [comment]
Can you send your `URL ` in the env.py file? @TheCastes

**Comment by TheCastes** [comment]
Here @MajideND  "https://www.google.com/maps/place/Google+UK/@51.5332608,-0.1304879,17z/data=!4m7!3m6!1s0x48761b3c54efa6e1:0xc7053ab04745950d!8m2!3d51.5332609!4d-0.1260032!9m1!1b1"

**Comment by MajideND** [comment]
@TheCastes There was a problem with the new release thanks for your report. Please let me know if there is any other problem after this update.
Furthermore, the URL you are using has more than 1800 reviews and crawling this number of reviews may take some minutes.
